language: node_js
node_js:
    - "0.12.0"
    - "4.0.0"
    - "5.0.0"
    - "6.0.0"
    - "7.0.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
